export * from '@banbury/core/src/device/addDevice'
export * from './deleteDevice'
export * from './updateDevice'
export * from './connect'
export * from './updateSyncStorage'
export * from './updateScorePreferences'
