name: Build and Release

on:
  push:
    branches:
      - main  # Triggers the workflow on every push to the main branch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Add Windows support
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.0'
          cache: 'npm'

      - name: Install Python and Build Tools for macOS
        if: runner.os == 'macOS'
        run: |
          brew install python-setuptools
          python3 -m venv .venv
          source .venv/bin/activate
          python3 -m pip install --upgrade pip setuptools

      - name: Install the Apple certificate
        if: runner.os == 'macOS'
        run: |
          # Create keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain

          # Import certificate
          echo "$CERTIFICATE_BASE64" | base64 --decode > certificate.p12
          security import certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain

          # Remove certificate file
          rm certificate.p12
        env:
          CERTIFICATE_BASE64: ${{ secrets.MACOS_CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          KEYCHAIN_PASSWORD: keychainpassword # This is just a temporary password for the build

      - name: Install dependencies
        run: npm install --force

      - name: Build the app
        run: npm run build

      - name: Package with Electron Builder
        run: npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          EP_PRE_RELEASE: true
          EP_DRAFT: false
          CSC_KEYCHAIN: build.keychain

      - name: Code Sign and Notarize macOS build
        if: runner.os == 'macOS'
        run: |
          xcode-select --install || true
          APP_NAME="Banbury.Cloud"
          VERSION=$(node -p "require('./package.json').version")
          
          echo "Listing contents of packages directory:"
          ls -R ./packages/
          
          # Notarize .app
          export APP_PATH="./packages/mac-arm64/${APP_NAME}.app"
          echo "Notarizing app: $APP_PATH"
          [ -e "$APP_PATH" ] && node ./scripts/notarize.ts
          
          # Notarize .dmg
          export APP_PATH="./packages/${APP_NAME}-${VERSION}-arm64.dmg"
          echo "Notarizing dmg: $APP_PATH"
          [ -e "$APP_PATH" ] && node ./scripts/notarize.ts
          
          # Notarize .zip
          export APP_PATH="./packages/${APP_NAME}-${VERSION}-arm64-mac.zip"
          echo "Notarizing zip: $APP_PATH"
          [ -e "$APP_PATH" ] && node ./scripts/notarize.ts
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-artifacts
          path: |
            packages/**/*
            dist/**/*.yml
            dist/**/*.yaml
          
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history for tagging

      - name: Download Linux Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-latest-artifacts
          path: ./packages

      - name: Download Windows Artifacts
        uses: actions/download-artifact@v3
        with:
          name: windows-latest-artifacts
          path: ./packages

      - name: Download macos Artifacts
        uses: actions/download-artifact@v3
        with:
          name: macos-latest-artifacts
          path: ./packages

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Create and push a new tag
        env:
          VERSION: ${{ env.VERSION }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "v$VERSION"
          git push https://$PAT@github.com/${{ github.repository }} "v$VERSION"
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.VERSION }}"
          files: |
            packages/**/*.AppImage
            packages/**/*.exe
            packages/**/*.dmg
            packages/**/*.zip
            packages/**/latest*.yml
            packages/**/latest*.yaml
            packages/**/*blockmap
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
